apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tz2ttp3ss-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:dedd2e969bbc995e3183ecd9a4aabf23438dd038@sha256:a7a417854fa73b59f987634d3dd07a52d93d2ff35ee9681565623c2dc6ef44fe
          name: container-image
